Fix the path in the executable file
Note: thanks to @akademy's comment in issue
https://github.com/mars-sim/mars-sim/issues/72

r4422
2018-08-02

## FIX
1. Correct the bad path inside executable file for the headless edition
2. Convert to Unix EOL

diff --git a/mars-sim-headless/src/main/resources/mars-sim b/mars-sim-headless/src/main/resources/mars-sim
--- a/mars-sim-headless/src/main/resources/mars-sim
+++ b/mars-sim-headless/src/main/resources/mars-sim
@@ -1,5 +1,18 @@
-#!/bin/bash
-if [[ $(java -version 2>&1) == *"OpenJDK"* ]]; then echo 'You are using OpenJDK'; else echo 'You are not using OpenJDK'; fi
+#!/usr/bin/env bash
+echo "Launching Mars Simulation Project..."
+if command -v java >/dev/null 2>&1;
+then
+    echo >&2 "Java found"
+else
+    echo >&2 "You don't have Java. Aborting"
+    exit 1
+fi
 
-#!/bin/sh
+if [[ $(java -version 2>&1) == *"OpenJDK"* ]]; 
+then 
+    echo 'You are using OpenJDK'
+else 
+    echo 'You are not using OpenJDK'
+fi
+
 java -Djava.util.logging.config.file=logging.properties -cp .::jars/ org.mars_sim.headless.MarsProjectHeadless -Xms256m -Xmx1024m -new
